language: cpp
compiler: g++
sudo: required
dist: trusty
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

branches:
  only: master

matrix:
  fast-finish: true

notifications:
  email: false

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
      - source-line: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - cmake
      - python-yaml
      - gcc-7
      - g++-7
      - clang-4.0
      - libc++-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-4.0" CC="clang-4.0"; fi

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make 
  - ./bin/test_graph
